### ISSUE TITLE
US 01.02.01 - View Attendee List

### ISSUE THREAD

**Issue by tammy-young** [CMPUT301W24T36/QuickScanR#3]
| User Story       | Description                                                                                                                                                      | Story Points | Risk Level |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|------------|
| US 01.02.01     | As an organizer, I want to view the list of attendees who have checked in to my event.                                                                         |      2        |      Low      |

**Comment by lykskai** [comment]
Closed via https://github.com/CMPUT301W24T36/QuickScanR/commit/b5f28f01f71cc89fd9a6a73bea9320c3fc83058a
