### ISSUE TITLE
US 01.05.01 - Track Attendees

### ISSUE THREAD

**Issue by ananyashukla2** [CMPUT301W24T36/QuickScanR#6]
| User Story       | Description                                                                                                                                                      | Story Points | Risk Level |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|------------|
| US 01.05.01     | As an organizer, I want to track real-time attendance and receive alerts for important milestones. |      7       |      Medium      |

**Comment by lykskai** [comment]
Solved via https://github.com/CMPUT301W24T36/QuickScanR/commit/b5f28f01f71cc89fd9a6a73bea9320c3fc83058a
